version: '3'
services:
  app:
    container_name: app
    build: ./php-fpm
    volumes:
      - ./app:/var/www/app
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./app:/var/www/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  php-fpm:
    build: ./php-fpm
    volumes:
      - ./source:/var/www/html
  db:
    container_name: mysql
    image: mysql:8
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - data-volume:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: pt
      MYSQL_USER: sample_user
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - 4040:80
    environment:
      PMA_HOST: ${DB_HOST}
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}

  mail-server:
    image: catatnight/postfix
    platform: linux/amd64
    ports:
      - 587:587
    environment:
      - MAIL_DOMAIN=example.com
      - MAIL_HOSTNAME=mail.example.com
    volumes:
          - ./mail/main.cf:/etc/postfix/main.cf
volumes:
  data-volume: